import { Inter } from 'next/font/google';
import { Header } from '../Components/Header/Header';
import { FC } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
const inter = Inter({ subsets: ['latin'] });
import LinksData from '../../data/data.json';

import styles from '@Components/styles/Home.module.scss';

interface Data {
  id: string;
  image: string;
  title: string;
  text: string;
}

interface LinksInfo {
  id: number;
  path: string;
  title: string;
}

interface Props {
  data: Data[];
}
const Home: FC<Props> = ({ data }) => {
  const linksInfo: LinksInfo[] = LinksData.linksInfo;
  return (
    <>
      <Head>
        <title>Akve_Design</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header links={linksInfo} />
      <main className={styles.main}>
        <Image
          alt={'design-photo'}
          src={'/images/138.png'}
          width={1905}
          height={824}
          style={{ width: '100vw', height: '75vh' }}
          className={styles['header-image']}
        />
        <div className={styles.designs}>
          {data.map((project) => {
            return (
              <Link
                key={project.id}
                href={`/work/${project.id}`}
                className={styles['design-link']}
              >
                <Image
                  alt={project.id}
                  src={project.image}
                  width={413}
                  height={232}
                  className={styles['home-image']}
                />
                <h2> {project.title}</h2>
              </Link>
            );
          })}
        </div>
      </main>
      <footer className={styles['page-footer']}>
        <p>Akve_Design 2023</p>
      </footer>
    </>
  );
};

export default Home;

export async function getServerSideProps() {
  const { projects } = await import('../../data/data.json');

  return {
    props: {
      data: projects,
    },
  };
}
